# -*- coding: utf-8 -*-
"""OOP Remaster V3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12a48KQTvQcpHYLdTDKJNGy9gwcqxNzkw
"""

import json
import os
import random

class Difficulty:
  def __init__(self, name, rounds, winning_numbers, score_value, xp_value, max_number):
    self.name = name
    self.rounds = rounds
    self.winning_numbers = winning_numbers
    self.xp_value = xp_value
    self.score_value = score_value
    self.max_number = max_number


SUPER_EASY = Difficulty(
        name = "Super Easy",
        rounds = 10,
        winning_numbers = [5, 7, 9, 4, 2],
        score_value = 1,
        xp_value = 5,
        max_number = 10

)

EASY = Difficulty(
        name = "Easy",
        rounds = 5,
        winning_numbers = [5, 7, 9],
        score_value = 3,
        xp_value = 15,
        max_number = 15
)

MEDIUM = Difficulty(
        name = "Medium",
        rounds = 3,
        winning_numbers = [5, 7, 9],
        score_value = 10,
        xp_value = 40,
        max_number = 25
)

HARD = Difficulty(
        name = "Hard",
        rounds = 1,
        winning_numbers = [5, 7],
        score_value = 25,
        xp_value = 75,
        max_number = 50
 )

SUPER_HARD = Difficulty(
        name = "Super Hard",
        rounds = 1,
        winning_numbers = [5],
        score_value = 75,
        xp_value = 150,
        max_number = 100
)

INSANE = Difficulty(
        name = "INSANE",
        rounds = 1,
        winning_numbers = [5],
        score_value = 500,
        xp_value = 500,
        max_number = 1000
)

################################################################################

class Game:
    def __init__(self, difficulty, player, leaderboard, save_manager):
        self.difficulty = difficulty
        self.player = player
        self.leaderboard = leaderboard
        self.save_manager = save_manager

    def play_game(self):
        print(f"\nDifficulty: {self.difficulty.name}")
        print(f"Welcome {self.player.name}!")

        while True:
            for _ in range(self.difficulty.rounds):
                self.play_round()

            if (
              self.difficulty == SUPER_EASY
              and self.player.current_game_score == self.difficulty.rounds * self.difficulty.score_value
            ):
              self.player.unlock_achievement(IMPOSSIBLE)

            self.player.add_game()
            self.player.update_best_score()
            self.player.current_game_score = 0
            self.leaderboard.update_player(self.player)
            self.save_manager.save(self.leaderboard.players)


            print(
              f"\nGame complete! "
              f"Total Score: {self.player.total_score} | "
              f"Total Wins: {self.player.total_wins}"
            )

            if not self.ask_play_again():
                print("\nThanks for playing!")
                break

    def play_round(self):
        self.player.add_round()
        number = self.generate_random_number()

        if number in self.difficulty.winning_numbers:
            self.player.add_win(self.difficulty.score_value)
            self.player.add_xp(self.difficulty.xp_value)
            self.player.add_difficulty_win(self.difficulty)

            print(
                f"{self.player.name}, you got {number}. "
                f"WINNER!!! +{self.difficulty.score_value} points!"
            )
            print(
                f"+{self.difficulty.xp_value} XP earned "
                f"({self.player.xp}/{self.player.xp_needed_for_next_level})"
            )

        else:
            self.player.add_loss()

            print(
                f"Better luck next time, {self.player.name}. "
                f"You got {number}."
                )

    def generate_random_number(self):
        return random.randint(1, self.difficulty.max_number)

    def ask_play_again(self):
        while True:
            again = input("\nPlay another game? (yes/no): ").strip().lower()

            if again == "yes":
                return True

            elif again == "no":
                return False

            else:
                print("Please enter yes or no.")

################################################################################

class Player:
    next_id = 1
    def __init__(self, name):
        self.name = name
        self.id = Player.next_id
        Player.next_id += 1
        self.total_wins = 0
        self.total_score = 0
        self.games_played = 0
        self.total_rounds = 0
        self.total_losses = 0
        self.best_score = 0
        self.current_streak = 0
        self.highest_streak = 0
        self.current_game_score = 0
        self.super_easy_wins = 0
        self.easy_wins = 0
        self.medium_wins = 0
        self.hard_wins = 0
        self.super_hard_wins = 0
        self.insane_wins = 0
        self.xp = 0
        self.level = 1
        self.achievements = set()

    def add_win(self, amount):
      self.total_wins += 1
      self.total_score += amount
      self.current_game_score += amount
      self.current_streak += 1

      if self.current_streak >= self.highest_streak:
        self.highest_streak = self.current_streak

      self.check_achievements()

    def add_loss(self):
      self.total_losses += 1
      self.current_streak = 0

      self.check_achievements()

    def add_difficulty_win(self, difficulty):
      if difficulty == SUPER_EASY:
        self.super_easy_wins += 1

      elif difficulty == EASY:
        self.easy_wins += 1

      elif difficulty == MEDIUM:
        self.medium_wins += 1

      elif difficulty == HARD:
        self.hard_wins += 1

      elif difficulty == SUPER_HARD:
        self.super_hard_wins += 1

      elif difficulty == INSANE:
        self.insane_wins += 1


      self.check_achievements()


    def add_round(self):
      self.total_rounds += 1

      self.check_achievements()

    def add_game(self):
      self.games_played += 1


    def unlock_achievement(self, achievement):
      if achievement.name not in self.achievements:
          self.achievements.add(achievement.name)

          print("ACHIEVEMENT UNLOCKED!")
          print(f"{achievement.name}")
          print(achievement.description)

    def check_achievements(self):

      # Total Wins
      if self.total_wins >= 1:
        self.unlock_achievement(FIRST_WIN)

      if self.total_wins >= 10:
        self.unlock_achievement(ROOKIE)

      if self.total_wins >= 100:
        self.unlock_achievement(EXPERIENCED)

      if self.total_wins >= 500:
        self.unlock_achievement(VETERAN)

      if self.total_wins >= 1000:
        self.unlock_achievement(LEGENDARY)

      # Levels
      if self.level >= 5:
        self.unlock_achievement(APPRENTICE)

      if self.level >= 20:
        self.unlock_achievement(WIZARD_OF_LUCK)

      if self.level >= 50:
        self.unlock_achievement(FORTUITOUS_WARLOCK)

      if self.level >= 100:
        self.unlock_achievement(THE_CHAMPION)

      # Lifetime Score
      if self.total_score >= 1000:
        self.unlock_achievement(DEDICATED)

      if self.total_score >= 10000:
        self.unlock_achievement(THE_BIGGEST_FISH)

      # Difficulty Wins
      if self.hard_wins >= 20:
        self.unlock_achievement(COURAGEOUS)

      if self.super_hard_wins >= 15:
        self.unlock_achievement(SUPREME)

      if self.insane_wins >= 1:
        self.unlock_achievement(INSANITY)

      if self.insane_wins >= 10:
        self.unlock_achievement(WTF)

      # Win on every difficulty
      if (
        self.super_easy_wins > 0
        and self.easy_wins > 0
        and self.medium_wins > 0
        and self.hard_wins > 0
        and self.super_hard_wins > 0
        and self.insane_wins > 0
      ):
        self.unlock_achievement(MASTER)

      if self.highest_streak >= 5:
        self.unlock_achievement(ON_FIRE)

      if self.highest_streak >= 10:
        self.unlock_achievement(UNSTOPPABLE)

      # Loss Achievements
      if self.total_losses >= 1:
        self.unlock_achievement(BAD_LUCK)

      if self.total_losses >= 10:
        self.unlock_achievement(ROUGH_START)

      if self.total_losses >= 100:
        self.unlock_achievement(UNLUCKY)

      if self.total_losses >= 500:
        self.unlock_achievement(CURSED)

      if self.total_losses >= 1000:
        self.unlock_achievement(THE_BLACK_HOLE)

      # Low Win Rate Achievement
      if self.total_rounds >= 100 and self.win_rate < 10:
        self.unlock_achievement(WHY_ARE_YOU_HERE)


      # Comeback Achievement
      if self.total_losses >= 50 and self.current_streak >= 10:
        self.unlock_achievement(THE_COMEBACK)


    def update_best_score(self):
      if self.current_game_score > self.best_score:
        self.best_score = self.current_game_score

    @property
    def xp_needed_for_next_level(self):
      return int(500 * (1.25 ** (self.level - 1)))

    def add_xp(self, amount):
      self.xp += amount

      while self.xp >= self.xp_needed_for_next_level:
        self.xp -= self.xp_needed_for_next_level
        self.level += 1

        print(f"\n yLEVEL UP! You reached Level {self.level}!")

      self.check_achievements()

    def xp_bar(self, length=10):
      progress = self.xp / self.xp_needed_for_next_level

      filled = int(progress * length)

      return "█" * filled + "░" * (length - filled)

    @property
    def win_rate(self):
      if self.total_rounds == 0:
        return 0

      return (self.total_wins / self.total_rounds) * 100


    def display_statistics(self):

      print("\n========== PLAYER STATISTICS ==========")
      print(f"Name: {self.name}")
      print(f"ID: {self.id}")

      print("\n---------- Progress ----------")
      print(f"Level : {self.level}")
      print(
          f"XP    : [{self.xp_bar()}] "
          f"{self.xp}/{self.xp_needed_for_next_level}"
      )

      print(f"Next Level: {self.xp_needed_for_next_level - self.xp} XP needed")

      print("\n---------- Overall ----------")

      print(f"Total Score : {self.total_score}")
      print(f"Total Wins  : {self.total_wins}")
      print(f"Total Losses : {self.total_losses}")
      print(f"Games Played : {self.games_played}")
      print(f"Rounds Played : {self.total_rounds}")
      print(f"Win Rate    : {self.win_rate:.1f}%")

      print("\n---------- Records ----------")

      print(f"Best Game Score : {self.best_score}")
      print(f"Highest Streak  : {self.highest_streak}")

      print("\n---------- Difficulty Wins ----------")

      print(f"Super Easy : {self.super_easy_wins}")
      print(f"Easy       : {self.easy_wins}")
      print(f"Medium     : {self.medium_wins}")
      print(f"Hard       : {self.hard_wins}")
      print(f"Super Hard : {self.super_hard_wins}")
      print(f"INSANE     : {self.insane_wins}")

      print("\n---------- Achievements ----------")

      if not self.achievements:
        print("No achievements unlocked yet.")

      else:
        print(f"Achievements Unlocked: {len(self.achievements)}")

        for achievement in sorted(self.achievements):
          print(f" 🏆 {achievement}")

      input("\nPress Enter to return to the menu...")

    def to_dict(self):
      return {
          "name": self.name,
          "id": self.id,
          "total_score": self.total_score,
          "total_wins": self.total_wins,
          "games_played": self.games_played,
          "total_rounds": self.total_rounds,
          "best_score": self.best_score,
          "total_losses": self.total_losses,
          "highest_streak": self.highest_streak,
          "current_streak": self.current_streak,
          "super_easy_wins": self.super_easy_wins,
          "easy_wins": self.easy_wins,
          "medium_wins": self.medium_wins,
          "hard_wins": self.hard_wins,
          "super_hard_wins": self.super_hard_wins,
          "insane_wins": self.insane_wins,
          "level": self.level,
          "xp": self.xp,
          "achievements": list(self.achievements)
      }

    @classmethod
    def from_dict(cls, player_id, data):
      player = cls(data["name"])

      player.id = data["id"]
      player.total_score = data["total_score"]
      player.total_wins = data["total_wins"]
      player.games_played = data["games_played"]
      player.total_rounds = data.get("total_rounds", 0)
      player.best_score = data.get("best_score", 0)
      player.total_losses = data.get("total_losses", 0)
      player.highest_streak = data.get("highest_streak", 0)
      player.current_streak = data.get("current_streak", 0)
      player.super_easy_wins = data.get("super_easy_wins", 0)
      player.easy_wins = data.get("easy_wins", 0)
      player.medium_wins = data.get("medium_wins", 0)
      player.hard_wins = data.get("hard_wins", 0)
      player.super_hard_wins = data.get("super_hard_wins", 0)
      player.insane_wins = data.get("insane_wins", 0)
      player.level = data.get("level", 1)
      player.xp = data.get("xp", 0)
      player.achievements = set(data.get("achievements", []))

      return player

################################################################################

class Achievement:
  def __init__(self, name, description):
    self.name = name
    self.description = description

FIRST_WIN = Achievement(
    name = "First Win",
    description = "Win your first round."
)

ROOKIE = Achievement(
    name = "Rookie",
    description = "Win your first 10 rounds"
)


EXPERIENCED = Achievement(
    name = "Experienced",
    description = "Win your first 100 rounds across any difficulty"
)

VETERAN = Achievement(
    name = "Veteran",
    description = "Win your first 500 rounds across any difficulty"
)

LEGENDARY = Achievement(
    name = "Legendary",
    description = "Win your first 1000 rounds across any difficulty"
)

INSANITY = Achievement(
    name = "Insanity",
    description = "Win a round on Insane Difficulty"
)

MASTER = Achievement(
    name = "Master",
    description = "Win a round on every difficulty"
)

IMPOSSIBLE = Achievement(
    name = "Impossible",
    description = "Win every round on Super Easy Difficulty"
)

APPRENTICE = Achievement(
    name = "Apprentice",
    description = "Reach level 5"
)

WIZARD_OF_LUCK = Achievement(
    name = "Wizard Of Luck",
    description = "Reach level 20"
)


FORTUITOUS_WARLOCK = Achievement(
    name = "Fortuitous Warlock",
    description = "Reach level 50"
)

THE_CHAMPION = Achievement(
    name = "The Champion",
    description = "Reach level 100"
)

DEDICATED = Achievement(
    name = "Dedicated",
    description = "score 1000 lifetime points"
)

THE_BIGGEST_FISH = Achievement(
    name = "The Biggest Fish",
    description = "score 10,000 lifetime points"
)

WTF = Achievement(
    name = "WTF",
    description = "Win 10 rounds on Insane Difficulty"
)

SUPREME = Achievement(
    name = "Supreme",
    description = "Win 15 rounds on Super Hard Difficulty"
)

COURAGEOUS = Achievement(
    name = "Courageous",
    description = "Win 20 rounds on Hard Difficulty"
)

ON_FIRE = Achievement(
    name="On Fire",
    description="Reach a 5-win streak."
)

UNSTOPPABLE = Achievement(
    name="Unstoppable",
    description="Reach a 10-win streak."
)

BAD_LUCK = Achievement(
    name = "Bad Luck",
    description = "Lose your first round."
)

ROUGH_START = Achievement(
    name = "Rough Start",
    description = "Lose 10 rounds."
)

UNLUCKY = Achievement(
    name = "Unlucky",
    description = "Lose 100 rounds."
)

CURSED = Achievement(
    name = "Cursed",
    description = "Lose 500 rounds."
)

THE_BLACK_HOLE = Achievement(
    name = "The Black Hole",
    description = "Lose 1000 rounds."
)

WHY_ARE_YOU_HERE = Achievement(
    name = "Why Are You Here?",
    description = "Play 100 rounds and win less than 10%."
)

THE_COMEBACK = Achievement(
    name = "The Comeback",
    description = "Lose 50 rounds, then win 10 rounds in a row."
)

################################################################################


class Leaderboard:
    def __init__(self, players = None):
      if players:
        self.players = players
      else:
        self.players = {}


    def find_player(self, player_id):
      return self.players.get(player_id)

    def find_players_by_name(self, name):
      matches = []

      for player in self.players.values():
        if player.name.lower() == name.lower():
          matches.append(player)

      return matches

    def update_player(self, player):
        self.players[player.id] = player

    def display_scores(self):
        print("\nLeaderboard:")

        ranked = sorted(
            self.players.values(),
            key=lambda player: (player.total_score, player.total_wins, player.highest_streak),
            reverse=True
        )

        if not ranked:
            print("No Players yet.")
            return

        for rank, player in enumerate(ranked, start=1):
            print(
                f"#{rank} | "
                f"ID: {player.id} | "
                f"{player.name} | "
                f"Lvl {player.level} | "
                f"Achievements: {len(player.achievements)} | "
                f"XP [{player.xp_bar()}] "
                f"XP: {player.xp}/{player.xp_needed_for_next_level} | "
                f"Score: {player.total_score} points | "
                f"Wins: {player.total_wins} wins | "
                f"{player.win_rate:.1f}% win rate | "
                f"{player.highest_streak} streak "

             )
################################################################################
class SaveManager:

  def __init__(self, filename):
    self.filename = filename

  def save(self, players):
    player_data = {}

    for player_id, player in players.items():
      player_data[player_id] = player.to_dict()

    with open(self.filename, "w") as file:
      json.dump(player_data, file, indent=4)

  def load_players(self):
    if not os.path.exists(self.filename):
      return {}

    with open(self.filename, "r") as file:
      data = json.load(file)

    players = {}

    for player_id, player_data in data.items():

      player = Player.from_dict(player_id, player_data)

      players[int(player_id)] = player

    if players:
      Player.next_id = max(players.keys()) + 1

    return players
################################################################################
def choose_difficulty():
  while True:
    print("\n=== Choose your Difficulty===")
    print("1. Super Easy")
    print("2. Easy")
    print("3. Medium")
    print("4. Hard")
    print("5. Super Hard")
    print("6. INSANE")

    choice = input("Select Difficulty: ").strip()

    if choice == "1":
      return SUPER_EASY

    elif choice == "2":
      return EASY

    elif choice == "3":
      return MEDIUM

    elif choice == "4":
      return HARD

    elif choice == "5":
      return SUPER_HARD

    elif choice == "6":
      return INSANE

    else:
      print("Please enter 1, 2, 3, 4, 5, or 6!")

################################################################################

def start():
    save_manager = SaveManager("players.json")

    players = save_manager.load_players()

    leaderboard = Leaderboard(players)

    while True:
        print("\n=== Player Login ===")

        while True:
            returning = input(
                "Are you a returning player? (yes/no): "
            ).strip().lower()

            if returning in ("yes", "no"):
                break

            print("Please enter yes or no.")

        if returning == "yes":

            while True:
                try:
                    player_id = int(input("Enter your player ID: "))

                except ValueError:
                    print("Please enter a valid ID.")
                    continue

                player = leaderboard.find_player(player_id)

                if player:
                    print(f"Welcome back, {player.name}!")
                    break

                print("No player found with that ID.")

        else:

            while True:
                name = input("Enter your name: ").strip()

                if name:
                    break

                print("Name cannot be blank.")

            matches = leaderboard.find_players_by_name(name)

            if matches:
                print("\nPlayers already using that name:")

                for existing in matches:
                    print(
                        f"ID: {existing.id} | "
                        f"{existing.total_score} points | "
                         f"{existing.total_wins} wins"
                    )

                while True:
                    choice = input(
                        "\nCreate a new player anyway? (yes/no): "
                    ).strip().lower()

                    if choice == "yes":
                        player = Player(name)
                        break

                    elif choice == "no":

                        while True:
                            try:
                                player_id = int(
                                    input(
                                        "Enter the player ID you want to use: "
                                    )
                                )

                            except ValueError:
                                print("Please enter a valid ID.")
                                continue

                            player = leaderboard.find_player(player_id)

                            if player and player.name.lower() == name.lower():
                                break

                            print(
                                "That ID does not belong to a player with that name."
                            )

                        break

                    else:
                        print("Please enter yes or no.")

            else:
                player = Player(name)

            if player.id not in leaderboard.players:
                leaderboard.update_player(player)
                save_manager.save(leaderboard.players)

            print(f"\nWelcome {player.name}!")
            if player.games_played == 0:
                print(f"Your player ID is {player.id}.")
                print("Keep this ID if you want your stats to continue.")

        difficulty = choose_difficulty()

        game = Game(
            difficulty = difficulty,
            player=player,
            leaderboard=leaderboard,
            save_manager = save_manager
        )

        game.play_game()

        while True:
          print("\n===== Post Game Menu =====")
          print("1. View Statistics")
          print("2. View Leaderboard")
          print("3. Continue")

          choice = input("Choose an option: ").strip()

          if choice == "1":
            player.display_statistics()

          elif choice == "2":
            leaderboard.display_scores()

          elif choice == "3":
            break

          else:
            print("Invalid choice.")

        while True:
            another_player = input(
                "\nWould another player like to play? (yes/no): "
            ).strip().lower()

            if another_player == "yes":
                break

            elif another_player == "no":
                print("\nFinal leaderboard:")
                leaderboard.display_scores()
                print("Thanks for playing!")
                save_manager.save(leaderboard.players)
                return

            else:
                print("Invalid input. Please enter 'yes' or 'no'.")


start()